=== HansMartinA/joframes/workspace/joframes-parent/joframes-language-syntax/src/main/resources/framework_specification_language_model.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
	xmlns:xsd="http://www.w3.org/2001/XMLSchema"
	elementFormDefault="qualified" attributeFormDefault="unqualified"
	targetNamespace="fwspec" xmlns="fwspec" version="1.0">
	<xsd:element name="framework-specification">
		<xsd:complexType>
			<xsd:sequence>
				<xsd:element name="resource-loader" minOccurs="0">
					<xsd:simpleType>
						<xsd:restriction base="xs:string">
							<xsd:pattern value="[A-Z]([A-Za-z0-9])*.class" />
						</xsd:restriction>
					</xsd:simpleType>
				</xsd:element>
				<xsd:element name="phases">
					<xsd:complexType>
						<xsd:sequence>
							<xsd:element name="start">
								<xsd:complexType>
									<xsd:sequence>
										<xsd:element name="explicit-declaration"
											type="explicitDeclarationType" maxOccurs="unbounded" />
									</xsd:sequence>
								</xsd:complexType>
							</xsd:element>
							<xsd:element name="end">
								<xsd:complexType>
									<xsd:sequence>
										<xsd:element name="explicit-declaration"
											type="explicitDeclarationType" />
									</xsd:sequence>
								</xsd:complexType>
							</xsd:element>
							<xsd:element name="working-phases">
								<xsd:complexType>
									<xsd:sequence>
										<xsd:element name="working" maxOccurs="unbounded">
											<xsd:complexType>
												<xsd:sequence>
													<xsd:choice minOccurs="0" maxOccurs="unbounded">
														<xsd:element name="rule-regex"
															type="xs:string" />
														<xsd:element name="rule-supertype"
															type="xs:string" />
														<xsd:element name="rule-block"
															type="rulesBlockType" />
													</xsd:choice>
												</xsd:sequence>
												<xsd:attribute name="threads" use="required"
													type="threadType" />
											</xsd:complexType>
										</xsd:element>
									</xsd:sequence>
								</xsd:complexType>
							</xsd:element>
						</xsd:sequence>
					</xsd:complexType>
				</xsd:element>
			</xsd:sequence>
			<xsd:attribute name="name" use="required"
				type="xs:string" />
		</xsd:complexType>
	</xsd:element>
	<xsd:simpleType name="threadType">
		<xsd:restriction base="xs:string">
			<xsd:enumeration value="multi" />
			<xsd:enumeration value="single" />
		</xsd:restriction>
	</xsd:simpleType>
	<xsd:simpleType name="blockQuantorType">
		<xsd:restriction base="xs:string">
			<xsd:enumeration value="for_all" />
		</xsd:restriction>
	</xsd:simpleType>
	<xsd:complexType name="rulesBlockType">
		<xsd:choice>
			<xsd:element name="rule-block" type="rulesBlockType" />
			<xsd:element name="explicit-declaration"
				type="explicitDeclarationType" />
		</xsd:choice>
		<xsd:attribute name="quantor" type="blockQuantorType"
			use="required" />
		<xsd:attribute name="class" type="xs:string"
			use="required" />
	</xsd:complexType>
	<xsd:complexType name="explicitDeclarationType">
		<xsd:sequence>
			<xsd:choice minOccurs="0" maxOccurs="unbounded">
				<xsd:element name="method-call" type="xs:string" />
				<xsd:element name="explicit-declaration"
					type="explicitDeclarationType" />
				<xsd:element name="static-call" type="xs:string" />
			</xsd:choice>
		</xsd:sequence>
		<xsd:attribute name="for_all" type="xs:string" />
	</xsd:complexType>
</xsd:schema>

=== HansMartinA/joframes/workspace/parent/api/src/test/resources/CompleteSpec.xml
<?xml version="1.0" encoding="UTF-8"?>
<framework-specification
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="framework_specification_language_model.xsd"
	xmlns="fwspec" name="CompleteSpec">
	<resource-loader>Test.class</resource-loader>
	<phases>
		<start>
			<explicit-declaration for_all="Ljava/lang/String">
				<method-call>Constructor</method-call>
			</explicit-declaration>
			<explicit-declaration for_all="Ljava/util/EventListener">
			    <method-call>Constructor</method-call>
			</explicit-declaration>
			<explicit-declaration for_all="Ljava/lang/Runtime">
			    <method-call>Constructor</method-call>
			</explicit-declaration>
		</start>
		<end>
			<explicit-declaration for_all="Ljava/lang/String">
				<explicit-declaration for_all="Ljava/lang/String">
				    <explicit-declaration for_all="Ljava/lang/String">
				        <explicit-declaration for_all="Ljava/lang/String">
				            <method-call>getCharAt(I)C</method-call>
				        </explicit-declaration>
				    </explicit-declaration>
				</explicit-declaration>
			</explicit-declaration>
		</end>
		<working-phases>
			<working threads="multi">
				<rule-block quantor="for_all" class="Ljavax/swing/JButton">
					<explicit-declaration>
						<method-call>addActionListener(Ljava/awt/event/ActionListener;)V</method-call>
						<method-call>addActionListener(Ljava/awt/event/ActionListener;)V</method-call>
						<explicit-declaration for_all="Ljavax/swing/JLabel">
						     <method-call>Constructor</method-call>
						</explicit-declaration>
					</explicit-declaration>
				</rule-block>
			</working>
			<working threads="single">
			    <rule-regex>.*</rule-regex>
			    <rule-supertype>Ljava/lang/Object</rule-supertype>
			    <rule-regex>.*</rule-regex>
			    <rule-block quantor="for_all" class="Ljava/lang/String">
			        <rule-block quantor="for_all" class="Ljava/lang/String">
			            <rule-block quantor="for_all" class="Ljava/lang/String">
			                <explicit-declaration>
			                    <static-call>Ljava/lang/Runtime getRuntime()Ljava/lang/Runtime</static-call>
			                    <explicit-declaration for_all="Ljava/lang/Object">
			                    </explicit-declaration>
			                    <method-call>getCharAt(I)C</method-call>
			                </explicit-declaration>
			            </rule-block>
			        </rule-block>
			    </rule-block>
			    <rule-supertype>Ljavax/swing/JFrame</rule-supertype>
			    <rule-supertype>Ljava/util/EventListener</rule-supertype>
			</working>
			<working threads="multi">
			</working>
		</working-phases>
	</phases>
</framework-specification>

=== HansMartinA/joframes/workspace/parent/api/src/test/resources/TestSpec.xml
<?xml version="1.0" encoding="UTF-8"?>
<framework-specification
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="framework_specification_language_model.xsd"
	xmlns="fwspec" name="Test-Application">
	<phases>
		<start>
			<explicit-declaration for_all="Ledu/kit/ipd/pp/joframes/api/test/framework/A">
				<static-call>Ledu/kit/ipd/pp/joframes/api/test/framework/A similarToMain([Ljava/lang/String;)V</static-call>
				<method-call>Constructor</method-call>
				<method-call>init()V</method-call>
				<method-call>start()V</method-call>
			</explicit-declaration>
			<explicit-declaration for_all="Ledu/kit/ipd/pp/joframes/api/test/framework/A2">
				<static-call>Ledu/kit/ipd/pp/joframes/api/test/framework/A similarToMain([Ljava/lang/String;)V</static-call>
				<method-call>Constructor</method-call>
				<method-call>initialize()V</method-call>
				<method-call>run()V</method-call>
			</explicit-declaration>
			<explicit-declaration for_all="Ledu/kit/ipd/pp/joframes/api/test/framework/A2">
				<static-call>Ledu/kit/ipd/pp/joframes/api/test/framework/A similarToMain([Ljava/lang/String;)V</static-call>
				<method-call>Constructor</method-call>
				<method-call>initialize(Ljava/lang/String;)V</method-call>
				<method-call>run()V</method-call>
			</explicit-declaration>
		</start>
		<end>
			<explicit-declaration>
				<explicit-declaration for_all="Ledu/kit/ipd/pp/joframes/api/test/framework/A">
					<method-call>destroy()V</method-call>
				</explicit-declaration>
				<explicit-declaration for_all="Ledu/kit/ipd/pp/joframes/api/test/framework/A2">
					<method-call>stop()V</method-call>
				</explicit-declaration>
			</explicit-declaration>
		</end>
		<working-phases>
			<working threads="multi">
				<rule-regex>doSomething.*</rule-regex>
				<rule-supertype>Ljava/util/EventListener</rule-supertype>
			</working>
			<working threads="single">
				<rule-supertype>Ljava/util/EventListener</rule-supertype>
				<rule-block quantor="for_all" class="Ledu/kit/ipd/pp/joframes/api/test/framework/BlockA">
					<rule-block quantor="for_all" class="Ledu/kit/ipd/pp/joframes/api/test/framework/BlockB">
						<explicit-declaration>
							<explicit-declaration for_all="Ledu/kit/ipd/pp/joframes/api/test/framework/BlockC">
								<method-call>biz()V</method-call>
							</explicit-declaration>
						</explicit-declaration>
					</rule-block>
				</rule-block>
			</working>
		</working-phases>
	</phases>
</framework-specification>

=== HansMartinA/joframes/workspace/parent/api/src/main/resources/JavaFX.xml
<?xml version="1.0" encoding="UTF-8"?>
<framework-specification
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="framework_specification_language_model.xsd"
	xmlns="fwspec" name="JavaFX">
	<phases>
		<start>
			<explicit-declaration>
				<static-call>main([Ljava/lang/String;)V</static-call>
				<explicit-declaration for_all="Ljavafx/application/Application">
					<method-call>Constructor</method-call>
					<method-call>init()V</method-call>
					<method-call>start(Ljavafx/stage/Stage;)V</method-call>
				</explicit-declaration>
			</explicit-declaration>
		</start>
		<end>
			<explicit-declaration for_all="Ljavafx/application/Application">
				<method-call>stop()V</method-call>
			</explicit-declaration>
		</end>
		<working-phases>
			<working threads="single">
				<rule-supertype>Ljavafx/event/EventHandler</rule-supertype>
			</working>
		</working-phases>
	</phases>
</framework-specification>

=== HansMartinA/joframes/workspace/joframes-parent/joframes-api/src/main/resources/Swing.xml
<?xml version="1.0" encoding="UTF-8"?>
<framework-specification
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="framework_specification_language_model.xsd"
	xmlns="fwspec" name="Swing">
	<phases>
		<start>
			<explicit-declaration>
				<static-call>main([Ljava/lang/String;)V</static-call>
			</explicit-declaration>
		</start>
		<end>
			<explicit-declaration>
			</explicit-declaration>
		</end>
		<working-phases>
			<working threads="single">
				<rule-supertype>Ljava/util/EventListener</rule-supertype>
			</working>
		</working-phases>
	</phases>
</framework-specification>

=== HansMartinA/joframes/workspace/parent/api/src/test/resources/InvalidSpec.xml
<?xml version="1.0" encoding="UTF-8"?>
<framework-specification
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="framework_specification_language_model.xsd"
	xmlns="fwspec" name="invalid-spec">
	<phases>
		<start>
			<explicit-declaration for_all="Ljava/lang/String">
				<method-call>Constructor</method-call>
			</explicit-declaration>
		</start>
		<end>
			<explicit-declaration>
			</explicit-declaration>
		</end>
		<working-phases>
			<working threads="multi">
				<rule-block quantor="for_all" class="Ljava/lang/String">
				</rule-block>
			</working>
			<working threads="single">
				<rule-regex>.*</rule-regex>
			</working>
		</working-phases>
	</phases>
</framework-specification>

=== HansMartinA/joframes/workspace/parent/api/src/main/resources/Servlets.xml
<?xml version="1.0" encoding="UTF-8"?>
<framework-specification
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="framework_specification_language_model.xsd"
	xmlns="fwspec" name="Servlets">
	<phases>
		<start>
			<explicit-declaration>
				<explicit-declaration for_all="Ljava/util/EventListener">
					<method-call>Constructor</method-call>
				</explicit-declaration>
				<explicit-declaration
					for_all="Ljavax/servlet/ServletContextListener">
					<method-call>contextInitialized(Ljavax/servlet/ServletContextEvent;)V
					</method-call>
				</explicit-declaration>
				<explicit-declaration for_all="Ljavax/servlet/Servlet">
					<method-call>Constructor</method-call>
					<method-call>init(Ljavax/servlet/ServletConfig;)V</method-call>
				</explicit-declaration>
			</explicit-declaration>
		</start>
		<end>
			<explicit-declaration>
				<explicit-declaration for_all="Ljavax/servlet/Servlet">
					<method-call>destroy()V</method-call>
				</explicit-declaration>
				<explicit-declaration
					for_all="Ljavax/servlet/ServletContextListener">
					<method-call>contextDestroyed(Ljavax/servlet/ServletContextEvent;)V
					</method-call>
				</explicit-declaration>
			</explicit-declaration>
		</end>
		<working-phases>
			<working threads="multi">
				<rule-block quantor="for_all" class="Ljavax/servlet/Servlet">
					<explicit-declaration>
						<explicit-declaration
							for_all="Ljavax/servlet/ServletRequestListener">
							<method-call>requestInitialized(Ljavax/servlet/ServletRequestEvent;)V
							</method-call>
						</explicit-declaration>
						<method-call>service(Ljavax/servlet/ServletRequest;Ljavax/servlet/ServletResponse;)V
						</method-call>
						<explicit-declaration
							for_all="Ljavax/servlet/ServletRequestListener">
							<method-call>requestDestroyed(Ljavax/servlet/ServletRequestEvent;)V
							</method-call>
						</explicit-declaration>
					</explicit-declaration>
				</rule-block>
			</working>
		</working-phases>
	</phases>
</framework-specification>
